data:
  clip: 5.0
  data_path: data\kronos_SHSE_601288_daily_2016-04-21_2026-04-17.csv
  lookback_window: 60
  max_context: 512
  predict_window: 10
  test_ratio: 0.05
  train_ratio: 0.8
  val_ratio: 0.15
device:
  device_id: 0
  use_cuda: true
experiment:
  description: 对农业银行(601288)进行日K线数据微调训练
  name: 601288_daily_prediction
  use_comet: false
experiment_description: 对农业银行(601288)进行日K线数据微调训练
model_paths:
  base_path: outputs/finetuned_models
  base_save_path: ''
  basemodel_save_name: basemodel
  exp_name: 601288_daily_finetune
  finetuned_tokenizer: ''
  pretrained_predictor: NeoQuasar/Kronos-base
  pretrained_tokenizer: NeoQuasar/Kronos-Tokenizer-base
  tokenizer_save_name: tokenizer
training:
  basemodel_epochs: 10
  batch_size: 8
  num_workers: 0
  predictor_learning_rate: 1.0e-06
  seed: 42
  tokenizer_epochs: 15
  tokenizer_learning_rate: 0.0002
